Add new input field called domain, with a feature flag
Syft-Application/podpora-bot pull request #970
Opened 2023-03-03 13:51 UTC by emekafredy

Add a new input field name `Domain` which has options on which team a slack bug ticket fits into

2023-03-06 11:27 UTC, keram commented
Hi @emekafredy cc @faisal-raza1208 ,
Overall the PR looks good. 
Unfortunately we made small mistake on Friday which will require some changes but it should not be complicated.
The new changes should be related to only IndeedFlex (Syft) support bot instance and
not to affect the default configuration.
That means we will need to:

 - discard changes in `support.showForm`
 - remove src/views/support/default/bug_domain_feature.json
 - update configs.syft.view method to return the feature flagged view. Something like we had in the `showForm`
    https://github.com/Syft-Application/podpora-bot/blob/master/src/lib/support_config.ts#L122-L124
   ```js
       view: function(key: string): View {
        let template_name = key;
        if (feature.is_enabled('bug_report_with_domain_select_box_feature') && key === 'bug') {
            template_name = 'bug_domain_feature'
        }

        return views.support.syft[template_name];
    },
   ```
  - update `configs.syft.messageText` to include the `domain` in the description if and only if the feature
    flag is enabled       

For visual changes it is good also provide some screenshots. From the slack modal preview:
<img width="516" alt="Screenshot 2023-03-06 at 11 23 46" src="https://user-images.githubusercontent.com/578608/223097208-edf344ea-924f-40d8-ba5d-0f93d55357db.png">

Which brings me to last point. I see for the title we used name `Product Area`. It will be good if keys in code match the user names so we should rename `domain` to `product_area`.
Similarly for the feature flag bit more expressive name. For example: `bug_report_with_product_area_select_box`

2023-03-06 16:08 UTC, emekafredy commented
This has been updated @keram

2023-03-06 17:09 UTC, kieran-flex commented
The "Product Area" label and "domain" key was kind of deliberate in that I'd asked the guys to do that, but in hindsight, but it's not the right way to do it. I was trying to make a distinction between us asking the end user about "Product Area" as that is something people will understand, but under the hood, mapping it to "Domain" as that is how PTE teams are structured and how we'll do assignment.

2023-03-07 10:42 UTC, keram requested changes

2023-03-07 10:42 UTC, keram commented on src/lib/support.ts
> +
can this new line be removed please

2023-03-07 10:42 UTC, keram commented on src/lib/support_config.ts
> +            let product_area_submission = ''
Hi @emekafredy 
Have you installed pre-commit hooks using the `overcommit` tool?
If yes, the commit should fail with error like this:

<img width="1171" alt="Screenshot 2023-03-07 at 10 35 33" src="https://user-images.githubusercontent.com/578608/223398275-0aba0336-d8fe-433e-98cc-7c743694b22a.png">

I really recommend using the pre-commit hooks as it save time.
I will add the linter check also to CI.
Meanwhile can you please run on this branch `npx eslint "**/*.ts" --fix` and address the reported warnings and errors?

2023-03-07 10:42 UTC, keram commented on src/lib/support_config.ts
> +            template_name = 'bug_domain_feature'
```suggestion
            template_name = 'bug_report_with_product_area'
```

2023-03-07 10:42 UTC, keram commented on src/views/support/syft/bug_domain_feature.json
> +{
Would suggest to rename 
`bug_domain_feature.json` to `bug_report_with_product_area.json` to be consistent.

2023-03-07 11:02 UTC, emekafredy commented
updated @keram

2023-03-07 11:15 UTC, keram approved these changes

2023-03-07 11:17 UTC, keram commented
Thank you @emekafredy as next step please prepare draft PR that will remove the feature flag and make the new feature being normal part of the code.

2023-03-07 11:17 UTC, merged